<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../../vendor/autoload.php";

use feldbusl\Plugins\CompetenceRecommender\Utils\CompetenceRecommenderTrait;
use srag\RemovePluginDataConfirm\CompetenceRecommender\AbstractRemovePluginDataConfirm;

/**
 * Class CompetenceRecommenderRemoveDataConfirm
 *
 * Generated by srag\PluginGenerator v0.9.7
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            Leonie Feldbusch <feldbusl@informatik.uni-freiburg.de>
 *
 * @ilCtrl_isCalledBy CompetenceRecommenderRemoveDataConfirm: ilUIPluginRouterGUI
 */
class CompetenceRecommenderRemoveDataConfirm extends AbstractRemovePluginDataConfirm {

	use CompetenceRecommenderTrait;
	const PLUGIN_CLASS_NAME = ilCompetenceRecommenderPlugin::class;
}
