<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../vendor/autoload.php";

use feldbusl\Plugins\CompetenceRecommender\Utils\CompetenceRecommenderTrait;
use srag\DIC\CompetenceRecommender\DICTrait;

/**
 * Class ilCompetenceRecommenderUIHookGUI
 *
 * Generated by srag\PluginGenerator v0.9.7
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author Leonie Feldbusch <feldbusl@informatik.uni-freiburg.de>
 */
class ilCompetenceRecommenderUIHookGUI extends ilUIHookPluginGUI {

	use DICTrait;
	use CompetenceRecommenderTrait;
	const PLUGIN_CLASS_NAME = ilCompetenceRecommenderPlugin::class;


	/**
	 * ilCompetenceRecommenderUIHookGUI constructor
	 */
	public function __construct() {

	}


	/**
	 * @param string $a_comp
	 * @param string $a_part
	 * @param array  $a_par
	 *
	 * @return array
	 */
	public function getHTML(/*string*/
		$a_comp, /*string*/
		$a_part, /*array*/
		$a_par = []): array {
		/*self::dic()->ctrl()->getLinkTargetByClass([
			ilUIPluginRouterGUI::class,
			CompetenceRecommenderGUI::class
		], CompetenceRecommenderGUI::CMD_SOME);*/

		// TODO: Implement getHTML

		return [ "mode" => self::KEEP, "html" => "" ];
	}
}
