<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../vendor/autoload.php";

use feldbusl\Plugins\CompetenceRecommender\Utils\CompetenceRecommenderTrait;
use srag\DIC\CompetenceRecommender\DICTrait;

/**
 * Class ilCompetenceRecommenderUIHookGUI
 *
 * Generated by srag\PluginGenerator v0.9.7
 *
 * @author Leonie Feldbusch <feldbusl@informatik.uni-freiburg.de>
 */
class ilCompetenceRecommenderUIHookGUI extends ilUIHookPluginGUI {

	use DICTrait;
	use CompetenceRecommenderTrait;
	const PLUGIN_CLASS_NAME = ilCompetenceRecommenderPlugin::class;

	/**
	 * @var ilCtrl
	 */
	protected $ctrl;

	/**
	 * @var ilLanguage
	 */
	protected $lng;

	/**
	 * @var ilTabsGUI
	 */
	protected $tabs;

	/**
	 * @var ilTemplate
	 */
	protected $tpl;

	/**
	 * @var ilHelpGUI
	 */
	protected $help;

	/**
	 * @var ilToolbarGUI
	 */
	protected $toolbar;

	/**
	 * @var ilAccessHandler
	 */
	var $access;


	/**
	 * ilCompetenceRecommenderUIHookGUI constructor
	 */
	public function __construct() {
		global $DIC;

		$this->ctrl = $DIC->ctrl();
		$this->lng = $DIC->language();
		//$this->tabs = $DIC->tabs();
		//$this->tpl = $DIC["tpl"];
		//$this->help = $DIC["ilHelp"];
		//$this->toolbar = $DIC->toolbar();
		$this->access = $DIC->access();
		$this->pl = ilCompetenceRecommenderPlugin::getInstance();
// übernehme aus Skill
	}


	/**
	 * @param string $a_comp
	 * @param string $a_part
	 * @param array  $a_par
	 *
	 * @return array
	 */
	public function getHTML(/*string*/
		$a_comp, /*string*/
		$a_part, /*array*/
		$a_par = []): array 
	{
		global $DIC;
		
		if ($a_comp == "Services/PersonalDesktop" && $a_part == "center_column") {
			return [ "mode" => ilUIHookPluginGUI::PREPEND, "html" => $this->pdTemplate() ];
		}
		return [ "mode" => ilUIHookPluginGUI::KEEP, "html" => "" ];
	}

	/**
	* write on desktop
	*
	* @return string HTML of div
	*/
	function pdTemplate()
	{
		global $DIC;

		$pl = $this->getPluginObject();	
		$btpl = $pl->getTemplate("tpl.comprecDesktop.html");	
		$btpl->setVariable("MESSAGE", "Hallo Welt");
		$button = $DIC->ui()->renderer()->render($DIC->ui()->factory()->button()->standard("weiter", $this->ctrl->getLinkTargetByClass([ilUIPluginRouterGUI::class, CompetenceRecommenderGUI::class], 'newPageTemplate')));
		$btpl->setVariable("BUTTON", $button);
		return $btpl->get();
	}


}
