<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

//require_once __DIR__ . "/../vendor/autoload.php";

use feldbusl\Plugins\CompetenceRecommender\Utils\CompetenceRecommenderTrait;
use srag\DIC\CompetenceRecommender\DICTrait;

/**
 * Class CompetenceRecommenderGUI
 *
 * Generated by srag\PluginGenerator v0.9.7
 *
 * @author Leonie Feldbusch <feldbusl@informatik.uni-freiburg.de>
 *
 * @ilCtrl_isCalledBy CompetenceRecommenderGUI: ilUIPluginRouterGUI
 */
class CompetenceRecommenderGUI {

	use DICTrait;
	use CompetenceRecommenderTrait;
	const PLUGIN_CLASS_NAME = ilCompetenceRecommenderPlugin::class;
    /** @var  ilCtrl */
    protected $ctrl;

    /** @var  ilTabsGUI */
    protected $tabs;

    /** @var  ilTemplate */
    public $tpl;

	/** @var  ilCompetenceRecommenderPlugin */
    public $pl;

	/**
	 * CompetenceRecommenderGUI constructor
	 */
	public function __construct() {
        	global $ilCtrl, $ilTabs, $tpl;
        	$this->ctrl = $ilCtrl;
        	$this->tabs = $ilTabs;
        	$this->tpl = $tpl;
		$this->pl = ilCompetenceRecommenderPlugin::getInstance();
	}


	/**
	 *
	 */
	public function executeCommand()/*: void*/ {
		if (!$this->pl->isActive()) {
			ilUtil::sendFailure('Activate Plugin first', true);
			ilUtil::redirect('index.php');
		}
		$cmd = ($this->ctrl->getCmd()) ? $this->ctrl->getCmd() : $this->getStandardCommand();
		switch ($cmd) {
			default:
				$this->performCommand($cmd);
				break;
		}

		return true;
	}


	/**
	 *
	 */
	protected function performCommand($cmd)/*: void*/ {
		global $tpl, $DIC;
		switch($cmd) {
			case 'compRecSettings':
				$tpl->getStandardTemplate();
				$tpl->setContent("Hier sollen die Kurse, die die Empfehlungen verwenden sollen, festgelegt werden können");
				$tpl->show();
				break;
			case 'compRecOverview':
			default:
				$this->overviewTemplate();
				break;
		}
	}


    	protected function overviewTemplate()
    	{
        	global $tpl, $DIC;

		$renderer = $DIC->ui()->renderer();
		$factory = $DIC->ui()->factory();

		// Extrahiere Reference ID
		$this->obj_ref_id = $_GET['obj_ref_id'];

		$result = $DIC->database()->query("SELECT * FROM object_data JOIN object_reference WHERE object_data.obj_id = object_reference.obj_id AND object_reference.ref_id = " .$this->obj_ref_id);

        	$tpl->getStandardTemplate();
		$tpl->setTitle("Meine Lernempfehlungen für " . $DIC->database()->fetchAssoc($result)["title"]);

		$items = $renderer->render($factory->image()->standard("Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/CompetenceRecommender/templates/BildMittel.png", "Platzhalter Item"));
		$items = $items ."<br/>". $renderer->render($factory->image()->standard("Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/CompetenceRecommender/templates/BildMittel.png", "Platzhalter Item"));
		$items = $items ."<br/>". $renderer->render($factory->image()->standard("Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/CompetenceRecommender/templates/BildMittel.png", "Platzhalter Item"));

        	$tpl->setContent("Hier sollen die konkreten Lernempfehlungen des Kurses erscheinen"."<br/>". $items);
		$tpl->show();
        	return;
    	}
}
