<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

//require_once __DIR__ . "/../vendor/autoload.php";

use feldbusl\Plugins\CompetenceRecommender\Utils\CompetenceRecommenderTrait;
use srag\DIC\CompetenceRecommender\DICTrait;

/**
 * Class CompetenceRecommenderGUI
 *
 * Generated by srag\PluginGenerator v0.9.7
 *
 * @author Leonie Feldbusch <feldbusl@informatik.uni-freiburg.de>
 *
 * @ilCtrl_isCalledBy CompetenceRecommenderGUI: ilUIPluginRouterGUI
 */
class CompetenceRecommenderGUI {

	use DICTrait;
	use CompetenceRecommenderTrait;
	const PLUGIN_CLASS_NAME = ilCompetenceRecommenderPlugin::class;
    /** @var  ilCtrl */
    protected $ctrl;

    /** @var  ilTabsGUI */
    protected $tabs;

    /** @var  ilTemplate */
    public $tpl;

	/** @var  ilCompetenceRecommenderPlugin */
    public $pl;

	/** @var  ilUIFramework */
	public $ui;

	/** @var  ilDB */
	public $db;

	/**
	 * CompetenceRecommenderGUI constructor
	 */
	public function __construct() {
		global $ilCtrl, $ilTabs, $tpl, $DIC;
        $this->ctrl = $ilCtrl;
        $this->tabs = $ilTabs;
        $this->tpl = $tpl;
		$this->ui = $DIC->ui();
		$this->db = $DIC->database();
		$this->pl = ilCompetenceRecommenderPlugin::getInstance();
	}


	/**
	 *
	 */
	public function executeCommand()/*: void*/ {
		if (!$this->pl->isActive()) {
			ilUtil::sendFailure('Activate Plugin first', true);
			ilUtil::redirect('index.php');
		}
		$cmd = ($this->ctrl->getCmd()) ? $this->ctrl->getCmd() : $this->getStandardCommand();
		switch ($cmd) {
			default:
				$this->performCommand($cmd);
				break;
		}

		return true;
	}


	/**
	 * @param $cmd
	 */
	protected function performCommand($cmd)/*: void*/ {
		switch($cmd) {
			case 'compRecOverview':
			default:
				$this->overviewTemplate();
				break;
		}
	}


    	protected function overviewTemplate()
    	{
			$renderer = $this->ui->renderer();
			$factory = $this->ui->factory();

			// Extrahiere Reference ID
			//$obj_ref_id = $_GET['obj_ref_id'];

			// $result = $this->db->query("SELECT * FROM object_data JOIN object_reference WHERE object_data.obj_id = object_reference.obj_id AND object_reference.ref_id = " .$obj_ref_id);

			$this->tpl->getStandardTemplate();
			$this->tpl->setTitle("Meine Lernempfehlungen");

			$items = $renderer->render($factory->image()->standard("Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/CompetenceRecommender/templates/BildMittel.png", "Platzhalter Item"));
			$items = $items ."<br/>". $renderer->render($factory->image()->standard("Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/CompetenceRecommender/templates/BildMittel.png", "Platzhalter Item"));
			$items = $items ."<br/>". $renderer->render($factory->image()->standard("Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/CompetenceRecommender/templates/BildMittel.png", "Platzhalter Item"));

			$this->tpl->setContent("Hier sollen die konkreten Lernempfehlungen des Kurses erscheinen"."<br/>". $items);
			$this->tpl->show();
        	return;
    	}
}
