<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

/**
 * Generated by srag\PluginGenerator v0.9.7
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author Leonie Feldbusch <feldbusl@informatik.uni-freiburg.de>
 */

$id = "comprec";
$version = "0.1.0";
$ilias_min_version = "5.3.0";
$ilias_max_version = "5.3.999";
$responsible = "Leonie Feldbusch";
$responsible_mail = "feldbusl@informatik.uni-freiburg.de";
